server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /backend/ {
        proxy_pass https://container-app-6c85.salmonpebble-6f51f89d.swedencentral.azurecontainerapps.io/api;

        proxy_http_version 1.1;
        proxy_ssl_server_name on;

        proxy_set_header Host container-app-6c85.salmonpebble-6f51f89d.swedencentral.azurecontainerapps.io;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 60s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf)$ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }
}
